### ISSUE TITLE
Stuck for new version

### ISSUE THREAD

**Issue by akt45** [IamSanjid/pporise#2]
its stuck on loading game data.. whats i must to do?
![capture](https://user-images.githubusercontent.com/39489513/44088519-9531e194-9fed-11e8-921f-7f22a4d934d8.PNG)

**Comment by Ixuari** [comment]
You need to find the updated config.json, or use a text editor to change the version to match the current version.

**Comment by akt45** [comment]
okay i know.. thanks so much.. i'll try it..

i try it for new version but still don't work.. anything wrong?
![capture2](https://user-images.githubusercontent.com/39489513/44130392-7ccce498-a077-11e8-8a36-264428eff0cd.PNG)
